version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    env_file:
      - .env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/config
